CREATE TABLE "addresses" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "telephone" varchar(255), "address" text, "city" varchar(255), "state" varchar(255), "postal_code" varchar(255), "addressable_id" integer NOT NULL, "addressable_type" varchar(255) NOT NULL);
CREATE TABLE "admins" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(50));
CREATE TABLE "business_types" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name_en" varchar(50), "name_zh_cn" varchar(50), "name_zh_tw" varchar(50));
CREATE TABLE "educations" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name_en" varchar(50), "name_zh_cn" varchar(50), "name_zh_tw" varchar(50));
CREATE TABLE "employers" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "business_name" varchar(50) NOT NULL, "business_type_id" integer NOT NULL, "telephone" varchar(50), "address" text, "city" varchar(50), "state" varchar(2), "postal_code" varchar(5), "confidential" boolean DEFAULT 'f' NOT NULL, "confirmed" varchar(255) DEFAULT 'f' NOT NULL, "subpath" varchar(50));
CREATE TABLE "experiences" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "job_category_id" integer, "resume_id" integer, "year_used" integer, "years_of_experience" integer);
CREATE TABLE "job_applications" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "job_seeker_id" integer, "employer_id" integer, "job_id" integer, "status" integer DEFAULT 0, "created_at" datetime, "updated_at" datetime);
CREATE TABLE "job_categories" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name_en" varchar(50), "name_zh_cn" varchar(50), "name_zh_tw" varchar(50));
CREATE TABLE "job_histories" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "resume_id" integer, "employer_name" varchar(50), "employer_city" varchar(50), "employer_state" varchar(2), "position" varchar(255));
CREATE TABLE "job_seekers" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(50) NOT NULL, "authorized_to_work_in_us" boolean DEFAULT 'f' NOT NULL, "gender" varchar(1) NOT NULL, "telephone" varchar(50), "address" text, "city" varchar(50), "state" varchar(2), "postal_code" varchar(5));
CREATE TABLE "jobs" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "postal_code" varchar(5), "employer_id" integer NOT NULL, "position_name" varchar(255) NOT NULL, "city" varchar(50), "state" varchar(2), "job_category_id" integer NOT NULL, "position_type_id" integer NOT NULL, "education_id" integer, "general_description" text, "job_requirements" text, "date_closed" date, "created_at" datetime, "updated_at" datetime, "experience_level" varchar(50));
CREATE TABLE "moderators" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(50));
CREATE TABLE "position_type" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar(255));
CREATE TABLE "position_types" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name_en" varchar(50), "name_zh_cn" varchar(50), "name_zh_tw" varchar(50));
CREATE TABLE "resumes" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "job_seeker_id" integer NOT NULL, "name" varchar(50), "public" boolean, "objective" text, "date_available" date, "desired_position_type_id" integer, "desired_monthly_salary" integer, "desired_hourly_pay_rate" integer, "preferred_locations" text, "education_id" integer, "institution" varchar(50));
CREATE TABLE "schema_migrations" ("version" varchar(255) NOT NULL);
CREATE TABLE "sessions" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "session_id" varchar(255) NOT NULL, "data" text, "created_at" datetime, "updated_at" datetime);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE "users" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "email" varchar(50) NOT NULL, "crypted_password" varchar(128) NOT NULL, "password_salt" varchar(20) NOT NULL, "persistence_token" varchar(128) NOT NULL, "perishable_token" varchar(20) NOT NULL, "profileable_id" integer NOT NULL, "profileable_type" varchar(30) NOT NULL, "active" boolean DEFAULT 't', "created_at" datetime, "updated_at" datetime, "login" varchar(50));
CREATE INDEX "index_addresses_on_id" ON "addresses" ("id");
CREATE INDEX "index_admins_on_id" ON "admins" ("id");
CREATE INDEX "index_business_types_on_id" ON "business_types" ("id");
CREATE INDEX "index_educations_on_id" ON "educations" ("id");
CREATE INDEX "index_employers_on_id" ON "employers" ("id");
CREATE INDEX "index_experiences_on_id" ON "experiences" ("id");
CREATE INDEX "index_job_applications_on_employer_id" ON "job_applications" ("employer_id");
CREATE INDEX "index_job_applications_on_id" ON "job_applications" ("id");
CREATE INDEX "index_job_applications_on_job_id" ON "job_applications" ("job_id");
CREATE INDEX "index_job_applications_on_job_seeker_id" ON "job_applications" ("job_seeker_id");
CREATE INDEX "index_job_categories_on_id" ON "job_categories" ("id");
CREATE INDEX "index_job_histories_on_id" ON "job_histories" ("id");
CREATE INDEX "index_job_seekers_on_id" ON "job_seekers" ("id");
CREATE INDEX "index_jobs_on_id" ON "jobs" ("id");
CREATE INDEX "index_moderators_on_id" ON "moderators" ("id");
CREATE INDEX "index_position_types_on_id" ON "position_types" ("id");
CREATE INDEX "index_resumes_on_id" ON "resumes" ("id");
CREATE INDEX "index_sessions_on_session_id" ON "sessions" ("session_id");
CREATE INDEX "index_sessions_on_updated_at" ON "sessions" ("updated_at");
CREATE INDEX "index_users_on_email" ON "users" ("email");
CREATE UNIQUE INDEX "unique_schema_migrations" ON "schema_migrations" ("version");
